fix: split commands by lines, check require_trailing_commas

diff --git a/.github/workflows/flutter_build_check.yml b/.github/workflows/flutter_build_check.yml
--- a/.github/workflows/flutter_build_check.yml
+++ b/.github/workflows/flutter_build_check.yml
@@ -19,5 +19,12 @@ jobs:
       - name: Run build check on all projects
         run: |
           for dir in $(find . -name 'pubspec.yaml' -not -path "./flutter_tools/*" -exec dirname {} \;); do
-            (cd $dir && flutter pub get && flutter analyze)
+            cd $dir
+            if [ ! -f $dir/analysis_options.yaml ] || ! grep -q "require_trailing_commas: true" $dir/analysis_options.yaml; then
+              echo "require_trailing_commas: true is missing in $dir/analysis_options.yaml"
+              exit 1
+            fi
+            flutter pub get
+            flutter analyze
+            cd -
           done
